Comment out tasks in the signing job

diff --git a/build/azure-pipelines/darwin/product-build-darwin-sign.yml b/build/azure-pipelines/darwin/product-build-darwin-sign.yml
--- a/build/azure-pipelines/darwin/product-build-darwin-sign.yml
+++ b/build/azure-pipelines/darwin/product-build-darwin-sign.yml
@@ -35,25 +35,25 @@ steps:
       git pull --no-rebase https://github.com/$(VSCODE_MIXIN_REPO).git $(node -p "require('./package.json').distro")
     displayName: Merge distro
 
-  - script: |
-      set -e
-      npx https://aka.ms/enablesecurefeed standAlone
-    timeoutInMinutes: 5
-    retryCountOnTaskFailure: 3
-    condition: and(succeeded(), eq(variables['ENABLE_TERRAPIN'], 'true'))
-    displayName: Switch to Terrapin packages
+  # - script: |
+  #     set -e
+  #     npx https://aka.ms/enablesecurefeed standAlone
+  #   timeoutInMinutes: 5
+  #   retryCountOnTaskFailure: 3
+  #   condition: and(succeeded(), eq(variables['ENABLE_TERRAPIN'], 'true'))
+  #   displayName: Switch to Terrapin packages
 
-  - script: |
-      set -e
-      for i in {1..3}; do # try 3 times, for Terrapin
-        yarn --cwd build --frozen-lockfile --check-files && break
-        if [ $i -eq 3 ]; then
-          echo "Yarn failed too many times" >&2
-          exit 1
-        fi
-        echo "Yarn failed $i, trying again..."
-      done
-    displayName: Install build dependencies
+  # - script: |
+  #     set -e
+  #     for i in {1..3}; do # try 3 times, for Terrapin
+  #       yarn --cwd build --frozen-lockfile --check-files && break
+  #       if [ $i -eq 3 ]; then
+  #         echo "Yarn failed too many times" >&2
+  #         exit 1
+  #       fi
+  #       echo "Yarn failed $i, trying again..."
+  #     done
+  #   displayName: Install build dependencies
 
   - download: current
     artifact: unsigned_vscode_client_darwin_$(VSCODE_ARCH)_archive
